### ISSUE TITLE
Error when used inside :has()

### ISSUE THREAD

**Issue by WebMechanic** [pascalduez/postcss-quantity-queries#22]
Hello,
love this plugin!! and I'm glad it still works in PostCSS 8. 

With `:has()` gaining [more browser support](https://caniuse.com/css-has) I tried using it, but the Plugin bails with an error: 

    Cannot read properties of undefined (reading 'apply')

```css
/* change list layout mode */
ul:has( li:exactly(2) ) {
  display: grid;
  grid-auto-flow: column;
}
```

Please also consider a proper [migration](https://evilmartians.com/chronicles/postcss-8-plugin-migration) to PostCSS 8.
