### ISSUE TITLE
Add a new `min-max` syntax

### ISSUE THREAD

**Issue by pascalduez** [pascalduez/postcss-quantity-queries#5]
Similar to:
http://dev.w3.org/csswg/mediaqueries/#mq-range-context
http://sassmeister.com/gist/indrekpaas/f48e5e34d329eaf44e37

``` css
ul > li:qty(>4) {
  color: rebeccapurple;
}
```
